name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy files via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          remote_host: ${{ secrets.HOST_DNS }}
          remote_user: ${{ secrets.USERNAME }}
          private_key: ${{ secrets.EC2_SSH_KEY }}
          target: ${{ secrets.TARGET_DIR }}
          source: "."   # adjust if needed

      - name: Execute remote commands (PM2 Restart)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            npm install --omit=dev
            npm run build
            pm2 restart next-app || pm2 start npm --name "next-app" -- start
